### ISSUE TITLE
http://charlottebrf.github.io/MigrateMe/landingpage.html

### ISSUE THREAD

**Issue by eddiejaoude** [charlottebrf/MigrateMe#2]
### Url

**GitHub Pages** url http://charlottebrf.github.io/MigrateMe/
### Description

Example **description** from website `Quaquaversal is a site that brings together stories from people around the world in one place.`

**Comment by eddiejaoude** [comment]
Screenshot to help...

<img width="999" alt="screenshot 2016-04-02 06 03 01" src="https://cloud.githubusercontent.com/assets/624760/14224562/98514166-f898-11e5-8a27-e95b2f290477.png">

**Comment by charlottebrf** [comment]
So I need to add description from website to our Github description.... Ok thanks @eddiejaoude

**Comment by charlottebrf** [comment]
![screen shot 2016-04-05 at 22 39 50](https://cloud.githubusercontent.com/assets/16884984/14298907/5be56632-fb7f-11e5-8002-3b0975664b8e.png)

Rectified @eddiejaoude  @smurfyrach ?

**Comment by eddiejaoude** [comment]
Perfect @charlottebrf 👍  With a screenshot as well...LOVE IT!! 😄
